[package]
name = "zed-plantuml"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1.2"

[dependencies.wasm-bindgen]
version = "0.2"
optional = true

[build]
target = "wasm32-wasip1"